dubbo:
  application:
    name: gmall-user-web
  consumer:
    timeout: 3000
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: cn.com.gmall.user.controller
  registry:
    address: zookeeper://192.168.133.129:2181
    check: false
    protocol: zookeeper
