dubbo:
  application:
    name: gmall-manage-web
  consumer:
    timeout: 30000
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: cn.com.gmall.manage.controller
  registry:
    address: zookeeper://192.168.133.129:2181
    check: false
    protocol: zookeeper

# 跨域配置
cn:
  com:
    address: http://127.0.0.1:8888
