dubbo:
  provider:
    timeout: 120000
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: cn.com.gmall
  registry:
    address: zookeeper://192.168.133.129:2181
    check: false
    protocol: zookeeper
  application:
    name: gmall-manage-service




